apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-cal-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: my-cal-app
  template:
    metadata:
      labels:
        app: my-cal-app
    spec:
      containers:
        - name: my-cal-app
          image: inam101001/my-cal-app:latest
          ports:
            - containerPort: 80
