apiVersion: v1
kind: Service
metadata:
  name: my-cal-app
spec:
  selector:
    app: my-cal-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
      nodePort: 30080
  type: NodePort

